### ISSUE TITLE
getCustomVariable not work with "label"

### ISSUE THREAD

**Issue by Sky-Cat** [VisualAppeal/Piwik-PHP-API#21]
$piwik->getCustomVariable($2, 'label=24285') does not work, because the second parameter must be a "label" rather than "segment".

Example:

http://demo.piwik.org/?module=API&method=CustomVariables.getCustomVariables&idSite=7&period=day&date=today&idSubtable=1&label=Forum%20status&format=xml&token_auth=anonymous - work

http://demo.piwik.org/?module=API&method=CustomVariables.getCustomVariables&idSite=7&period=day&date=today&idSubtable=1&segment=Forum%20status&format=xml&token_auth=anonymous - not work

**segment=Forum%20status** replaced by **label=Forum%20status**.

I am sorry for my bad english.

**Comment by thelfensdrfer** [comment]
You mean the method `$piwik->getCustomVariables` with an **s** at the end? I dont know what the label paramter should be good for. According to the api it does not exist and if you do not include the paramter the response does not change:

http://demo.piwik.org/?module=API&method=CustomVariables.getCustomVariables&idSite=7&period=day&date=today&idSubtable=1&label=Forum%20status&format=xml&token_auth=anonymous - your example

http://demo.piwik.org/?module=API&method=CustomVariables.getCustomVariables&idSite=7&period=day&date=today&idSubtable=1&format=xml&token_auth=anonymous - example according to the api

Same response with and without the **label** paramter.

**Comment by Sky-Cat** [comment]
I`m sorry. Here is the correct link:
http://stat.yarcom.ru/?module=API&method=CustomVariables.getCustomVariablesValuesFromNameId&idSite=1&period=day&date=today&idSubtable=2&label=24285&format=xml&token_auth=anonymous - work

http://stat.yarcom.ru/?module=API&method=CustomVariables.getCustomVariablesValuesFromNameId&idSite=1&period=day&date=today&idSubtable=2&segment=24285&format=xml&token_auth=anonymous - not work. `<error message="The segment '24285' is not valid."/>`

All labels: http://stat.yarcom.ru/?module=API&method=CustomVariables.getCustomVariablesValuesFromNameId&idSite=1&period=day&date=today&idSubtable=2&format=xml&token_auth=anonymous

**Comment by Sky-Cat** [comment]
Your function getCustomVariable() contains the [parameter "segment"](https://github.com/VisualAppeal/Piwik-PHP-API/blob/master/src/Piwik.php#L1219), but it does not work in this case.
Parameter "label" work.

**Comment by thelfensdrfer** [comment]
I see your point but according to the official api there is no parameter "label" https://developer.piwik.org/api-reference/reporting-api. Probably this is a bug?

**Comment by Sky-Cat** [comment]
Yes, maybe it was a mistake. [Here](http://forum.piwik.org/read.php?2,93837) already written about it. The parameter "label" is described [in this section](http://developer.piwik.org/api-reference/reporting-api#optional-api-parameters), but in CustomVariables.getCustomVariablesValuesFromNameId()  this parameter is not present.

**Comment by thelfensdrfer** [comment]
Ahh ok. I think the best way to implement this is with an array for optional parameters for all methods. I will open a new issue for this.

**Comment by Sky-Cat** [comment]
Thank you

**Comment by thelfensdrfer** [comment]
This should be fixed now, therefore see https://github.com/VisualAppeal/Piwik-PHP-API#120-20150503
