### ISSUE TITLE
SitesManager.updateSite - missing few parameters

### ISSUE THREAD

**Issue by Sky-Cat** [VisualAppeal/Piwik-PHP-API#29]
The functions updateSite lacks two parameters: idSite, settings = ''.

See: http://developer.piwik.org/api-reference/reporting-api#SitesManager

Piwik-PHP-API: 1.2.0
Piwik: 2.14.2

**Comment by thelfensdrfer** [comment]
idSite is always appended (https://github.com/VisualAppeal/Piwik-PHP-API/blob/master/src/Piwik.php#L425) but settings is missing. I will fix it tomorrow.
