### ISSUE TITLE
Can you make the _request() function public instead of private

### ISSUE THREAD

**Issue by echo1consulting** [VisualAppeal/Piwik-PHP-API#6]
By having the _request function private, i cannot use it in another class to make custom api calls.

e.g: 

    class myClass {

        function __construct(  $site = '', $token = '', $site_id = '' ) {

            $this->piwik = new \Piwik( $site, $token, $site_id);

            $this->piwik->_request( 'API.getPiwikVersion' );

        }

    }

Thank You!

**Comment by thelfensdrfer** [comment]
Any thoughts @echo1consulting ?

**Comment by thelfensdrfer** [comment]
I will close this issue for now. Please feel free to comment or reopen if you have any details!
